# Generated by Django 4.0 on 2023-03-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cbcreport_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbcreport',
            name='file_path',
        ),
        migrations.AlterField(
            model_name='cbcreport',
            name='cbcgrading',
            field=models.FileField(blank=True, null=True, upload_to='media/cbcgrading'),
        ),
    ]
