# Generated by Django 4.0 on 2023-03-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_cbcreport_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbcreport',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cbcreport',
            name='cbcgrading',
            field=models.FileField(blank=True, null=True, upload_to='cbcgrading/'),
        ),
    ]
