# Generated by Django 4.0 on 2023-03-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cbcreport_image_alter_cbcreport_cbcgrading'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbcreport',
            name='pdffile',
            field=models.FileField(blank=True, null=True, upload_to='media/pdf/'),
        ),
        migrations.AlterField(
            model_name='cbcreport',
            name='cbcgrading',
            field=models.FileField(blank=True, null=True, upload_to='media/cbcgrading/'),
        ),
        migrations.AlterField(
            model_name='cbcreport',
            name='image',
            field=models.ImageField(default='', upload_to='media/images/'),
        ),
    ]
