# Generated by Django 4.0 on 2023-03-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cbcreport_pdffile_alter_cbcreport_cbcgrading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbcreport',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='cbcreport',
            name='cbcrawfile',
            field=models.FileField(blank=True, null=True, upload_to='media/cbcrawfile/'),
        ),
    ]
