# Generated by Django 4.0 on 2023-03-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cbcreport_created_time_alter_cbcreport_cbcrawfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbcreport',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
